name: GitAction
on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up environment variables
        run: |
          echo MYSQL_HOST=localhost >> $GITHUB_ENV
          echo MYSQL_PORT=3306 >> $GITHUB_ENV
          echo MYSQL_USER=root >> $GITHUB_ENV
          echo MYSQL_PASSWORD= >> $GITHUB_ENV
          echo MYSQL_DBNAME=todoappdb >> $GITHUB_ENV
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/todoapp:latest
